language: ruby
rvm:
  - 2.3.4

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--color' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

before_script:
  - psql -c "DROP DATABASE IF EXISTS \"railsTraining_test\";" -U postgres
  - psql -c "CREATE DATABASE \"railsTraining_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

cache:
  bundler: true
